String MAIN_page = 
String("<!DOCTYPE html>")
+ String("<html>")
+ String("<head>")
+ String("  <title>Radiotelescope controller</title>")
+ String("</head>")
+ String("")
+ String("<body>")
+ String("<div id='demo'>")
+ String("  <h1>Radiotelescope controller</h1>")
+ String("  <h2>Current Position</h2>")
+ String("  <table>")
+ String("    <tr>")
+ String("      <th>RA</th>")
+ String("      <th>DEC</th>")
+ String("    </tr>")
+ String("    <tr>")
+ String("      <td><span id='currentPositionRA'/></td>")
+ String("      <td><span id='currentPositionDEC'/></td>")
+ String("    </tr>")
+ String("  </table>")
+ String("  ")
+ String("  <h2>Motion control</h2>")
+ String("  <table>")
+ String("    <tr>")
+ String("      <th>RA</th>")
+ String("      <th>DEC</th>")
+ String("    </tr>")
+ String("    <tr>")
+ String("      <td><input type='text' id='newRA' style='text-align: center'></td>")
+ String("      <td><input type='text' id='newDEC' style='text-align: center'></td>")
+ String("    </tr>")
+ String("  </table>")
+ String("  ")
+ String("  <h2>Functions</h2>")

+ String("  <button type='button' style='width: 79%; height: 50px; margin-bottom: 10px' onclick='Goto()'><b>GOTO</b></button>")
+ String("  <button type='button' id='GotoState' style='width: 20%; height: 50px; margin-bottom: 10px'>----</button><br>")

+ String("  <button type='button' style='width: 79%; height: 50px; margin-bottom: 10px' onclick='Track()'><b>TRACK</b></button>")
+ String("  <button type='button' id='TrackState' style='width: 20%; height: 50px; margin-bottom: 10px'>----</button><br>")

+ String("  <button type='button' style='width: 79%; height: 50px; margin-bottom: 10px' onclick='Park()'><b>PARK</b></button>")
+ String("  <button type='button' id='ParkState' style='width: 20%; height: 50px; margin-bottom: 10px'>----</button><br>")

+ String("  <button type='button' style='width: 79%; height: 50px; margin-bottom: 10px' onclick='SetParkPosition()'><b>SET PARK POSITION</b></button>")
+ String("  <button type='button' id='SetParkPositionState' style='width: 20%; height: 50px; margin-bottom: 10px'>----</button><br>")

+ String("  ")
+ String("</div>")
+ String("<div>")
+ String("</div>")
+ String("")
+ String("<style>")
+ String("table {")
+ String("  font-family: arial, sans-serif;")
+ String("  border-collapse: collapse;")
+ String("  width: 100%;")
+ String("}")
+ String("")
+ String("td, th {")
+ String("  text-align: center;")
+ String("  padding: 8px;")
+ String("}")
+ String("")
+ String("tr:nth-child(even) {")
+ String("  background-color: #dddddd;")
+ String("}")
+ String("</style>")
+ String("")
+ String("<script>")
+ String("setInterval(function()")
+ String("{")
+ String("  getData();")
+ String("}, 1500);")
+ String("")
+ String("function getData()")
+ String("{")
+ String("  var xhttp = new XMLHttpRequest();")
+ String("  xhttp.onreadystatechange = function()")
+ String("  {")
+ String("    if (this.readyState == 4 && this.status == 200)")
+ String("    {")
+ String("      var splitResponse = this.responseText.split('|');")
+ String("      document.getElementById('currentPositionRA').innerHTML = splitResponse[0].split('-')[0];")
+ String("      document.getElementById('currentPositionDEC').innerHTML = splitResponse[0].split('-')[1];")
+ String("      document.getElementById('TrackState').innerHTML = splitResponse[1];")
+ String("      document.getElementById('ParkState').innerHTML = splitResponse[2];")
+ String("      document.getElementById('SetParkPositionState').innerHTML = 'RA: ' + splitResponse[3].split('-')[0] + ' - DEC: ' + splitResponse[3].split('-')[1];")
+ String("    }")
+ String("  };")
+ String("  xhttp.open('GET', 'updatePage', true);")
+ String("  xhttp.send();")
+ String("}")
+ String("")
+ String("function Goto()")
+ String("{")
+ String("  var xhttp = new XMLHttpRequest();")
+ String("  var newRA = document.getElementById('newRA').value;")
+ String("  var newDEC = document.getElementById('newDEC').value;")
+ String("  xhttp.open('GET', 'goto?newRA='+newRA+'&newDEC='+newDEC, true);")
+ String("  xhttp.send();")
+ String("}")
+ String("")
+ String("function Track()")
+ String("{")
+ String("  var xhttp = new XMLHttpRequest();")
+ String("  xhttp.open('GET', 'track', true);")
+ String("  xhttp.send();")
+ String("}")
+ String("")
+ String("function Park()")
+ String("{")
+ String("  var xhttp = new XMLHttpRequest();")
+ String("  xhttp.open('GET', 'park', true);")
+ String("  xhttp.send();")
+ String("}")
+ String("")
+ String("function SetParkPosition()")
+ String("{")
+ String("  var answer = confirm('Are you sure?');")
+ String("  if(answer)")
+ String("  {")
+ String("    var xhttp = new XMLHttpRequest();")
+ String("    xhttp.open('GET', 'setParkPosition', true);")
+ String("    xhttp.send();")
+ String("  }")
+ String("}")
+ String("")
+ String("</script>")
+ String("</body>")
+ String("</html>");
